services:
  app:
    build: .
    container_name: probudget_backend
    ports:
      - "8001:80"
    restart: always
    mem_limit: 512m
    cpus: "0.5"
    networks:
      - probudget_net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

networks:
  probudget_net:
    external: true